// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module TOP_AWGN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        din_address0,
        din_ce0,
        din_q0,
        dout_address0,
        dout_ce0,
        dout_we0,
        dout_d0,
        grp_fu_1089_p_din0,
        grp_fu_1089_p_din1,
        grp_fu_1089_p_opcode,
        grp_fu_1089_p_dout0,
        grp_fu_1089_p_ce,
        grp_fu_1093_p_din0,
        grp_fu_1093_p_din1,
        grp_fu_1093_p_opcode,
        grp_fu_1093_p_dout0,
        grp_fu_1093_p_ce,
        grp_fu_1097_p_din0,
        grp_fu_1097_p_din1,
        grp_fu_1097_p_opcode,
        grp_fu_1097_p_dout0,
        grp_fu_1097_p_ce,
        grp_fu_1101_p_din0,
        grp_fu_1101_p_din1,
        grp_fu_1101_p_opcode,
        grp_fu_1101_p_dout0,
        grp_fu_1101_p_ce,
        grp_fu_1105_p_din0,
        grp_fu_1105_p_din1,
        grp_fu_1105_p_opcode,
        grp_fu_1105_p_dout0,
        grp_fu_1105_p_ce,
        grp_fu_1109_p_din0,
        grp_fu_1109_p_din1,
        grp_fu_1109_p_opcode,
        grp_fu_1109_p_dout0,
        grp_fu_1109_p_ce,
        grp_fu_1113_p_din0,
        grp_fu_1113_p_din1,
        grp_fu_1113_p_opcode,
        grp_fu_1113_p_dout0,
        grp_fu_1113_p_ce,
        grp_fu_1117_p_din0,
        grp_fu_1117_p_din1,
        grp_fu_1117_p_opcode,
        grp_fu_1117_p_dout0,
        grp_fu_1117_p_ce,
        grp_fu_1121_p_din0,
        grp_fu_1121_p_din1,
        grp_fu_1121_p_opcode,
        grp_fu_1121_p_dout0,
        grp_fu_1121_p_ce,
        grp_fu_1125_p_din0,
        grp_fu_1125_p_din1,
        grp_fu_1125_p_opcode,
        grp_fu_1125_p_dout0,
        grp_fu_1125_p_ce,
        grp_fu_1129_p_din0,
        grp_fu_1129_p_din1,
        grp_fu_1129_p_opcode,
        grp_fu_1129_p_dout0,
        grp_fu_1129_p_ce,
        grp_fu_1133_p_din0,
        grp_fu_1133_p_din1,
        grp_fu_1133_p_opcode,
        grp_fu_1133_p_dout0,
        grp_fu_1133_p_ce,
        grp_fu_1197_p_din0,
        grp_fu_1197_p_din1,
        grp_fu_1197_p_opcode,
        grp_fu_1197_p_dout0,
        grp_fu_1197_p_ce,
        grp_fu_1137_p_din0,
        grp_fu_1137_p_din1,
        grp_fu_1137_p_dout0,
        grp_fu_1137_p_ce,
        grp_fu_1141_p_din0,
        grp_fu_1141_p_din1,
        grp_fu_1141_p_dout0,
        grp_fu_1141_p_ce,
        grp_fu_1145_p_din0,
        grp_fu_1145_p_din1,
        grp_fu_1145_p_dout0,
        grp_fu_1145_p_ce,
        grp_fu_1149_p_din0,
        grp_fu_1149_p_din1,
        grp_fu_1149_p_dout0,
        grp_fu_1149_p_ce,
        grp_fu_1153_p_din0,
        grp_fu_1153_p_din1,
        grp_fu_1153_p_dout0,
        grp_fu_1153_p_ce,
        grp_fu_1157_p_din0,
        grp_fu_1157_p_din1,
        grp_fu_1157_p_dout0,
        grp_fu_1157_p_ce,
        grp_fu_1161_p_din0,
        grp_fu_1161_p_din1,
        grp_fu_1161_p_dout0,
        grp_fu_1161_p_ce,
        grp_fu_1165_p_din0,
        grp_fu_1165_p_din1,
        grp_fu_1165_p_dout0,
        grp_fu_1165_p_ce,
        grp_fu_1169_p_din0,
        grp_fu_1169_p_din1,
        grp_fu_1169_p_dout0,
        grp_fu_1169_p_ce,
        grp_fu_1173_p_din0,
        grp_fu_1173_p_din1,
        grp_fu_1173_p_dout0,
        grp_fu_1173_p_ce,
        grp_fu_1177_p_din0,
        grp_fu_1177_p_din1,
        grp_fu_1177_p_dout0,
        grp_fu_1177_p_ce,
        grp_fu_1181_p_din0,
        grp_fu_1181_p_din1,
        grp_fu_1181_p_dout0,
        grp_fu_1181_p_ce,
        grp_fu_1185_p_din0,
        grp_fu_1185_p_din1,
        grp_fu_1185_p_dout0,
        grp_fu_1185_p_ce,
        grp_fu_1081_p_din0,
        grp_fu_1081_p_din1,
        grp_fu_1081_p_dout0,
        grp_fu_1081_p_ce,
        grp_fu_1085_p_din0,
        grp_fu_1085_p_din1,
        grp_fu_1085_p_dout0,
        grp_fu_1085_p_ce,
        grp_fu_1189_p_din0,
        grp_fu_1189_p_din1,
        grp_fu_1189_p_dout0,
        grp_fu_1189_p_ce,
        grp_fu_1193_p_din0,
        grp_fu_1193_p_din1,
        grp_fu_1193_p_dout0,
        grp_fu_1193_p_ce
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state39 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] din_address0;
output   din_ce0;
input  [63:0] din_q0;
output  [2:0] dout_address0;
output   dout_ce0;
output   dout_we0;
output  [63:0] dout_d0;
output  [63:0] grp_fu_1089_p_din0;
output  [63:0] grp_fu_1089_p_din1;
output  [0:0] grp_fu_1089_p_opcode;
input  [63:0] grp_fu_1089_p_dout0;
output   grp_fu_1089_p_ce;
output  [63:0] grp_fu_1093_p_din0;
output  [63:0] grp_fu_1093_p_din1;
output  [0:0] grp_fu_1093_p_opcode;
input  [63:0] grp_fu_1093_p_dout0;
output   grp_fu_1093_p_ce;
output  [63:0] grp_fu_1097_p_din0;
output  [63:0] grp_fu_1097_p_din1;
output  [1:0] grp_fu_1097_p_opcode;
input  [63:0] grp_fu_1097_p_dout0;
output   grp_fu_1097_p_ce;
output  [63:0] grp_fu_1101_p_din0;
output  [63:0] grp_fu_1101_p_din1;
output  [1:0] grp_fu_1101_p_opcode;
input  [63:0] grp_fu_1101_p_dout0;
output   grp_fu_1101_p_ce;
output  [63:0] grp_fu_1105_p_din0;
output  [63:0] grp_fu_1105_p_din1;
output  [1:0] grp_fu_1105_p_opcode;
input  [63:0] grp_fu_1105_p_dout0;
output   grp_fu_1105_p_ce;
output  [63:0] grp_fu_1109_p_din0;
output  [63:0] grp_fu_1109_p_din1;
output  [1:0] grp_fu_1109_p_opcode;
input  [63:0] grp_fu_1109_p_dout0;
output   grp_fu_1109_p_ce;
output  [63:0] grp_fu_1113_p_din0;
output  [63:0] grp_fu_1113_p_din1;
output  [1:0] grp_fu_1113_p_opcode;
input  [63:0] grp_fu_1113_p_dout0;
output   grp_fu_1113_p_ce;
output  [63:0] grp_fu_1117_p_din0;
output  [63:0] grp_fu_1117_p_din1;
output  [1:0] grp_fu_1117_p_opcode;
input  [63:0] grp_fu_1117_p_dout0;
output   grp_fu_1117_p_ce;
output  [63:0] grp_fu_1121_p_din0;
output  [63:0] grp_fu_1121_p_din1;
output  [1:0] grp_fu_1121_p_opcode;
input  [63:0] grp_fu_1121_p_dout0;
output   grp_fu_1121_p_ce;
output  [63:0] grp_fu_1125_p_din0;
output  [63:0] grp_fu_1125_p_din1;
output  [1:0] grp_fu_1125_p_opcode;
input  [63:0] grp_fu_1125_p_dout0;
output   grp_fu_1125_p_ce;
output  [63:0] grp_fu_1129_p_din0;
output  [63:0] grp_fu_1129_p_din1;
output  [1:0] grp_fu_1129_p_opcode;
input  [63:0] grp_fu_1129_p_dout0;
output   grp_fu_1129_p_ce;
output  [63:0] grp_fu_1133_p_din0;
output  [63:0] grp_fu_1133_p_din1;
output  [1:0] grp_fu_1133_p_opcode;
input  [63:0] grp_fu_1133_p_dout0;
output   grp_fu_1133_p_ce;
output  [63:0] grp_fu_1197_p_din0;
output  [63:0] grp_fu_1197_p_din1;
output  [1:0] grp_fu_1197_p_opcode;
input  [63:0] grp_fu_1197_p_dout0;
output   grp_fu_1197_p_ce;
output  [63:0] grp_fu_1137_p_din0;
output  [63:0] grp_fu_1137_p_din1;
input  [63:0] grp_fu_1137_p_dout0;
output   grp_fu_1137_p_ce;
output  [63:0] grp_fu_1141_p_din0;
output  [63:0] grp_fu_1141_p_din1;
input  [63:0] grp_fu_1141_p_dout0;
output   grp_fu_1141_p_ce;
output  [63:0] grp_fu_1145_p_din0;
output  [63:0] grp_fu_1145_p_din1;
input  [63:0] grp_fu_1145_p_dout0;
output   grp_fu_1145_p_ce;
output  [63:0] grp_fu_1149_p_din0;
output  [63:0] grp_fu_1149_p_din1;
input  [63:0] grp_fu_1149_p_dout0;
output   grp_fu_1149_p_ce;
output  [63:0] grp_fu_1153_p_din0;
output  [63:0] grp_fu_1153_p_din1;
input  [63:0] grp_fu_1153_p_dout0;
output   grp_fu_1153_p_ce;
output  [63:0] grp_fu_1157_p_din0;
output  [63:0] grp_fu_1157_p_din1;
input  [63:0] grp_fu_1157_p_dout0;
output   grp_fu_1157_p_ce;
output  [63:0] grp_fu_1161_p_din0;
output  [63:0] grp_fu_1161_p_din1;
input  [63:0] grp_fu_1161_p_dout0;
output   grp_fu_1161_p_ce;
output  [63:0] grp_fu_1165_p_din0;
output  [63:0] grp_fu_1165_p_din1;
input  [63:0] grp_fu_1165_p_dout0;
output   grp_fu_1165_p_ce;
output  [63:0] grp_fu_1169_p_din0;
output  [63:0] grp_fu_1169_p_din1;
input  [63:0] grp_fu_1169_p_dout0;
output   grp_fu_1169_p_ce;
output  [63:0] grp_fu_1173_p_din0;
output  [63:0] grp_fu_1173_p_din1;
input  [63:0] grp_fu_1173_p_dout0;
output   grp_fu_1173_p_ce;
output  [63:0] grp_fu_1177_p_din0;
output  [63:0] grp_fu_1177_p_din1;
input  [63:0] grp_fu_1177_p_dout0;
output   grp_fu_1177_p_ce;
output  [63:0] grp_fu_1181_p_din0;
output  [63:0] grp_fu_1181_p_din1;
input  [63:0] grp_fu_1181_p_dout0;
output   grp_fu_1181_p_ce;
output  [63:0] grp_fu_1185_p_din0;
output  [63:0] grp_fu_1185_p_din1;
input  [63:0] grp_fu_1185_p_dout0;
output   grp_fu_1185_p_ce;
output  [63:0] grp_fu_1081_p_din0;
output  [63:0] grp_fu_1081_p_din1;
input  [63:0] grp_fu_1081_p_dout0;
output   grp_fu_1081_p_ce;
output  [63:0] grp_fu_1085_p_din0;
output  [63:0] grp_fu_1085_p_din1;
input  [63:0] grp_fu_1085_p_dout0;
output   grp_fu_1085_p_ce;
output  [63:0] grp_fu_1189_p_din0;
output  [63:0] grp_fu_1189_p_din1;
input  [63:0] grp_fu_1189_p_dout0;
output   grp_fu_1189_p_ce;
output  [63:0] grp_fu_1193_p_din0;
output  [63:0] grp_fu_1193_p_din1;
input  [63:0] grp_fu_1193_p_dout0;
output   grp_fu_1193_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg din_ce0;
reg dout_ce0;
reg dout_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] j_6_reg_1573;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
wire    ap_block_state8_pp0_stage0_iter5;
wire    ap_block_state9_pp0_stage0_iter6;
wire    ap_block_state10_pp0_stage0_iter7;
wire    ap_block_state11_pp0_stage0_iter8;
wire    ap_block_state12_pp0_stage0_iter9;
wire    ap_block_state13_pp0_stage0_iter10;
wire    ap_block_state14_pp0_stage0_iter11;
wire    ap_block_state15_pp0_stage0_iter12;
wire    ap_block_state16_pp0_stage0_iter13;
wire    ap_block_state17_pp0_stage0_iter14;
wire    ap_block_state18_pp0_stage0_iter15;
wire    ap_block_state19_pp0_stage0_iter16;
wire    ap_block_state20_pp0_stage0_iter17;
wire    ap_block_state21_pp0_stage0_iter18;
wire    ap_block_state22_pp0_stage0_iter19;
wire    ap_block_state23_pp0_stage0_iter20;
wire    ap_block_state24_pp0_stage0_iter21;
wire    ap_block_state25_pp0_stage0_iter22;
wire    ap_block_state26_pp0_stage0_iter23;
wire    ap_block_state27_pp0_stage0_iter24;
wire    ap_block_state28_pp0_stage0_iter25;
wire    ap_block_state29_pp0_stage0_iter26;
wire    ap_block_state30_pp0_stage0_iter27;
wire    ap_block_state31_pp0_stage0_iter28;
wire    ap_block_state32_pp0_stage0_iter29;
wire    ap_block_state33_pp0_stage0_iter30;
wire    ap_block_state34_pp0_stage0_iter31;
wire    ap_block_state35_pp0_stage0_iter32;
wire    ap_block_state36_pp0_stage0_iter33;
wire    ap_block_state37_pp0_stage0_iter34;
wire    ap_block_state38_pp0_stage0_iter35;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] j_6_reg_1573_pp0_iter1_reg;
reg   [3:0] j_6_reg_1573_pp0_iter2_reg;
reg   [3:0] j_6_reg_1573_pp0_iter3_reg;
reg   [3:0] j_6_reg_1573_pp0_iter4_reg;
reg   [3:0] j_6_reg_1573_pp0_iter5_reg;
reg   [3:0] j_6_reg_1573_pp0_iter6_reg;
reg   [3:0] j_6_reg_1573_pp0_iter7_reg;
reg   [3:0] j_6_reg_1573_pp0_iter8_reg;
reg   [3:0] j_6_reg_1573_pp0_iter9_reg;
reg   [3:0] j_6_reg_1573_pp0_iter10_reg;
reg   [3:0] j_6_reg_1573_pp0_iter11_reg;
reg   [3:0] j_6_reg_1573_pp0_iter12_reg;
reg   [3:0] j_6_reg_1573_pp0_iter13_reg;
reg   [3:0] j_6_reg_1573_pp0_iter14_reg;
reg   [3:0] j_6_reg_1573_pp0_iter15_reg;
reg   [3:0] j_6_reg_1573_pp0_iter16_reg;
reg   [3:0] j_6_reg_1573_pp0_iter17_reg;
reg   [3:0] j_6_reg_1573_pp0_iter18_reg;
reg   [3:0] j_6_reg_1573_pp0_iter19_reg;
reg   [3:0] j_6_reg_1573_pp0_iter20_reg;
reg   [3:0] j_6_reg_1573_pp0_iter21_reg;
reg   [3:0] j_6_reg_1573_pp0_iter22_reg;
reg   [3:0] j_6_reg_1573_pp0_iter23_reg;
reg   [3:0] j_6_reg_1573_pp0_iter24_reg;
reg   [3:0] j_6_reg_1573_pp0_iter25_reg;
reg   [3:0] j_6_reg_1573_pp0_iter26_reg;
reg   [3:0] j_6_reg_1573_pp0_iter27_reg;
reg   [3:0] j_6_reg_1573_pp0_iter28_reg;
reg   [3:0] j_6_reg_1573_pp0_iter29_reg;
reg   [3:0] j_6_reg_1573_pp0_iter30_reg;
reg   [3:0] j_6_reg_1573_pp0_iter31_reg;
reg   [3:0] j_6_reg_1573_pp0_iter32_reg;
wire   [0:0] icmp_ln17_fu_650_p2;
reg   [0:0] icmp_ln17_reg_1579;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter1_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter2_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter3_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter4_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter5_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter6_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter7_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter8_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter9_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter10_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter11_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter12_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter13_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter14_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter15_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter16_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter17_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter18_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter19_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter20_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter21_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter22_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter23_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter24_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter25_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter26_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter27_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter28_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter29_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter30_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter31_reg;
reg   [0:0] icmp_ln17_reg_1579_pp0_iter32_reg;
wire   [0:0] trunc_ln229_fu_666_p1;
reg   [0:0] trunc_ln229_reg_1583;
wire   [63:0] tmp_uniform_fu_1296_p3;
reg   [63:0] tmp_uniform_reg_1607;
reg   [63:0] tmp_uniform_reg_1607_pp0_iter2_reg;
reg   [63:0] tmp_uniform_reg_1607_pp0_iter3_reg;
reg   [63:0] tmp_uniform_reg_1607_pp0_iter4_reg;
reg   [63:0] tmp_uniform_reg_1607_pp0_iter5_reg;
reg   [63:0] tmp_uniform_reg_1607_pp0_iter6_reg;
reg   [63:0] tmp_uniform_reg_1607_pp0_iter7_reg;
reg   [63:0] tmp_uniform_reg_1607_pp0_iter8_reg;
reg   [63:0] tmp_uniform_reg_1607_pp0_iter9_reg;
wire   [0:0] or_ln443_fu_1354_p2;
reg   [0:0] or_ln443_reg_1617;
reg   [0:0] or_ln443_reg_1617_pp0_iter3_reg;
reg   [0:0] or_ln443_reg_1617_pp0_iter4_reg;
reg   [0:0] or_ln443_reg_1617_pp0_iter5_reg;
reg   [0:0] or_ln443_reg_1617_pp0_iter6_reg;
reg   [0:0] or_ln443_reg_1617_pp0_iter7_reg;
reg   [0:0] or_ln443_reg_1617_pp0_iter8_reg;
reg   [0:0] or_ln443_reg_1617_pp0_iter9_reg;
wire   [0:0] and_ln443_fu_1360_p2;
reg   [0:0] and_ln443_reg_1622;
reg   [0:0] and_ln443_reg_1622_pp0_iter3_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter4_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter5_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter6_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter7_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter8_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter9_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter10_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter11_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter12_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter13_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter14_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter15_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter16_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter17_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter18_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter19_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter20_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter21_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter22_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter23_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter24_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter25_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter26_reg;
reg   [0:0] and_ln443_reg_1622_pp0_iter27_reg;
wire   [63:0] tmp_472_fu_1366_p3;
reg   [63:0] t2_reg_1638;
wire   [63:0] t3_fu_1383_p1;
wire   [0:0] or_ln443_4_fu_1393_p2;
reg   [0:0] or_ln443_4_reg_1648;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter11_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter12_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter13_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter14_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter15_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter16_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter17_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter18_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter19_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter20_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter21_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter22_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter23_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter24_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter25_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter26_reg;
reg   [0:0] or_ln443_4_reg_1648_pp0_iter27_reg;
reg   [63:0] z_10_reg_1673;
wire   [63:0] z_9_fu_1398_p3;
reg   [63:0] z_9_reg_1678;
reg   [63:0] z_9_reg_1678_pp0_iter12_reg;
reg   [63:0] z_9_reg_1678_pp0_iter13_reg;
reg   [63:0] z_9_reg_1678_pp0_iter14_reg;
reg   [63:0] z_9_reg_1678_pp0_iter15_reg;
reg   [63:0] z_9_reg_1678_pp0_iter16_reg;
reg   [63:0] z_9_reg_1678_pp0_iter17_reg;
reg   [63:0] z_9_reg_1678_pp0_iter18_reg;
reg   [63:0] z_9_reg_1678_pp0_iter19_reg;
reg   [63:0] z_9_reg_1678_pp0_iter20_reg;
reg   [63:0] z_9_reg_1678_pp0_iter21_reg;
wire   [63:0] r_21_fu_1405_p3;
reg   [63:0] r_21_reg_1683;
reg   [63:0] r_21_reg_1683_pp0_iter13_reg;
reg   [63:0] r_21_reg_1683_pp0_iter14_reg;
reg   [63:0] r_21_reg_1683_pp0_iter15_reg;
reg   [63:0] r_21_reg_1683_pp0_iter16_reg;
reg   [63:0] r_21_reg_1683_pp0_iter17_reg;
reg   [63:0] r_21_reg_1683_pp0_iter18_reg;
reg   [63:0] r_21_reg_1683_pp0_iter19_reg;
wire   [63:0] p1_fu_1413_p3;
wire   [63:0] q1_fu_1421_p3;
wire   [63:0] p2_fu_1429_p3;
wire   [63:0] q2_fu_1437_p3;
wire   [63:0] p3_fu_1445_p3;
wire   [63:0] q3_fu_1453_p3;
wire   [63:0] p4_fu_1461_p3;
wire   [63:0] q4_fu_1469_p3;
reg   [63:0] f2_reg_1792;
reg   [63:0] f2_reg_1792_pp0_iter19_reg;
wire   [63:0] p5_fu_1477_p3;
wire   [63:0] f2_9_fu_1485_p3;
wire   [63:0] p6_fu_1492_p3;
reg   [63:0] t19_reg_1833;
reg   [63:0] f1_1_reg_1838;
wire   [63:0] f1_4_fu_1500_p3;
reg   [63:0] f1_4_reg_1844;
reg   [63:0] f2_10_reg_1849;
wire   [63:0] result_fu_1527_p3;
reg   [63:0] result_reg_1854;
wire   [63:0] j_cast_fu_1534_p1;
reg   [63:0] j_cast_reg_1859;
reg   [63:0] j_cast_reg_1859_pp0_iter34_reg;
reg   [63:0] div_reg_1864;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state2;
wire    grp_seedInitialization_fu_432_ap_ready;
wire    grp_seedInitialization_fu_432_ap_done;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state4;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg   [8:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_address0;
reg    rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0;
reg    rngMT19937ICN_uniformRNG_mt_odd_0_V_we0;
reg   [31:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_d0;
wire   [31:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_q0;
reg   [8:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_address1;
reg    rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1;
wire   [31:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_q1;
reg   [8:0] rngMT19937ICN_uniformRNG_mt_even_0_V_address0;
reg    rngMT19937ICN_uniformRNG_mt_even_0_V_ce0;
reg    rngMT19937ICN_uniformRNG_mt_even_0_V_we0;
reg   [31:0] rngMT19937ICN_uniformRNG_mt_even_0_V_d0;
wire   [31:0] rngMT19937ICN_uniformRNG_mt_even_0_V_q0;
reg   [8:0] rngMT19937ICN_uniformRNG_mt_even_0_V_address1;
reg    rngMT19937ICN_uniformRNG_mt_even_0_V_ce1;
wire   [31:0] rngMT19937ICN_uniformRNG_mt_even_0_V_q1;
wire    grp_seedInitialization_fu_432_ap_start;
wire    grp_seedInitialization_fu_432_ap_idle;
wire   [8:0] grp_seedInitialization_fu_432_this_mt_odd_0_address0;
wire    grp_seedInitialization_fu_432_this_mt_odd_0_ce0;
wire    grp_seedInitialization_fu_432_this_mt_odd_0_we0;
wire   [31:0] grp_seedInitialization_fu_432_this_mt_odd_0_d0;
wire   [8:0] grp_seedInitialization_fu_432_this_mt_odd_0_address1;
wire    grp_seedInitialization_fu_432_this_mt_odd_0_ce1;
wire   [8:0] grp_seedInitialization_fu_432_this_mt_odd_1_address0;
wire    grp_seedInitialization_fu_432_this_mt_odd_1_ce0;
wire    grp_seedInitialization_fu_432_this_mt_odd_1_we0;
wire   [31:0] grp_seedInitialization_fu_432_this_mt_odd_1_d0;
wire   [8:0] grp_seedInitialization_fu_432_this_mt_even_0_address0;
wire    grp_seedInitialization_fu_432_this_mt_even_0_ce0;
wire    grp_seedInitialization_fu_432_this_mt_even_0_we0;
wire   [31:0] grp_seedInitialization_fu_432_this_mt_even_0_d0;
wire   [8:0] grp_seedInitialization_fu_432_this_mt_even_1_address0;
wire    grp_seedInitialization_fu_432_this_mt_even_1_ce0;
wire    grp_seedInitialization_fu_432_this_mt_even_1_we0;
wire   [31:0] grp_seedInitialization_fu_432_this_mt_even_1_d0;
wire   [31:0] grp_seedInitialization_fu_432_ap_return_0;
wire   [31:0] grp_seedInitialization_fu_432_ap_return_1;
wire   [31:0] grp_seedInitialization_fu_432_ap_return_2;
wire   [31:0] grp_seedInitialization_fu_432_ap_return_3;
reg   [31:0] ap_phi_mux_p_0_0_0616_phi_fu_413_p4;
wire   [31:0] ap_phi_reg_pp0_iter1_p_0_0_0616_reg_410;
reg   [31:0] ap_phi_mux_p_0_0_0604_phi_fu_424_p4;
wire   [31:0] ap_phi_reg_pp0_iter1_p_0_0_0604_reg_421;
reg    grp_seedInitialization_fu_432_ap_start_reg;
wire   [63:0] zext_ln587_fu_702_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln587_8_fu_712_p1;
wire   [63:0] zext_ln587_9_fu_805_p1;
reg   [31:0] rngMT19937ICN_uniformRNG_x_k_p_2_V_1_fu_288;
reg   [31:0] lhs_V_fu_292;
reg   [31:0] p_Val2_s_fu_296;
reg   [3:0] j_fu_300;
wire   [3:0] add_ln17_fu_656_p2;
reg   [31:0] p_Val2_172_fu_304;
wire   [31:0] ret_42_fu_780_p2;
wire   [7:0] p_cast13_fu_662_p1;
wire   [3:0] addr_head_p_3_V_fu_670_p2;
wire   [7:0] addr_head_p_m_p_1_V_fu_676_p2;
wire   [2:0] r_s_fu_682_p4;
wire   [6:0] trunc_ln_fu_692_p4;
wire  signed [7:0] sext_ln587_fu_708_p1;
wire   [0:0] tmp_463_fu_732_p3;
wire   [29:0] tmp_s_fu_744_p4;
wire   [30:0] tmp_V_fu_754_p3;
wire   [0:0] p_Result_312_fu_740_p1;
wire   [31:0] select_ln722_fu_766_p3;
wire   [31:0] xor_ln1544_fu_774_p2;
wire   [31:0] zext_ln1043_fu_762_p1;
wire   [2:0] tmp_77_fu_788_p4;
wire   [9:0] r_22_fu_797_p3;
wire   [20:0] r_fu_814_p4;
wire   [31:0] zext_ln1691_fu_824_p1;
wire   [31:0] pre_result_V_51_fu_828_p2;
wire   [0:0] tmp_464_fu_834_p3;
wire   [2:0] tmp_78_fu_842_p4;
wire   [0:0] tmp_465_fu_852_p3;
wire   [0:0] tmp_466_fu_860_p3;
wire   [1:0] tmp_79_fu_868_p4;
wire   [0:0] tmp_467_fu_878_p3;
wire   [0:0] tmp_468_fu_886_p3;
wire   [1:0] tmp_80_fu_894_p4;
wire   [0:0] trunc_ln1542_fu_904_p1;
wire   [31:0] ret_fu_908_p19;
wire   [31:0] pre_result_V_52_fu_948_p2;
wire   [2:0] tmp_81_fu_954_p4;
wire   [5:0] tmp_82_fu_964_p4;
wire   [1:0] tmp_83_fu_974_p4;
wire   [31:0] ret_40_fu_984_p7;
wire   [31:0] pre_result_V_53_fu_1000_p2;
wire   [13:0] r_14_fu_1006_p4;
wire   [31:0] zext_ln1691_11_fu_1016_p1;
wire   [31:0] pre_result_V_fu_1020_p2;
reg   [31:0] p_Result_313_fu_1032_p4;
reg   [31:0] l_fu_1042_p3;
wire   [31:0] sub_ln947_fu_1054_p2;
wire   [31:0] lsb_index_fu_1060_p2;
wire   [30:0] tmp_469_fu_1066_p4;
wire   [5:0] trunc_ln950_fu_1086_p1;
wire   [5:0] sub_ln950_fu_1090_p2;
wire   [31:0] zext_ln950_fu_1096_p1;
wire   [31:0] lshr_ln950_fu_1100_p2;
wire   [31:0] shl_ln952_fu_1106_p2;
wire   [31:0] or_ln952_10_fu_1112_p2;
wire   [31:0] and_ln952_fu_1118_p2;
wire   [0:0] tmp_470_fu_1130_p3;
wire   [0:0] p_Result_314_fu_1144_p3;
wire   [0:0] xor_ln952_fu_1138_p2;
wire   [31:0] sub_ln962_fu_1164_p2;
wire   [63:0] zext_ln960_fu_1082_p1;
wire   [63:0] zext_ln962_fu_1170_p1;
wire   [0:0] icmp_ln949_fu_1076_p2;
wire   [0:0] icmp_ln952_fu_1124_p2;
wire   [31:0] add_ln961_fu_1188_p2;
wire   [63:0] zext_ln961_fu_1194_p1;
wire   [0:0] icmp_ln961_fu_1152_p2;
wire   [0:0] select_ln949_fu_1180_p3;
wire   [0:0] and_ln952_13_fu_1158_p2;
wire   [63:0] lshr_ln961_fu_1198_p2;
wire   [63:0] shl_ln962_fu_1174_p2;
wire   [0:0] select_ln961_fu_1204_p3;
wire   [63:0] m_fu_1212_p3;
wire   [63:0] zext_ln964_fu_1220_p1;
wire   [63:0] m_53_fu_1224_p2;
wire   [62:0] m_56_fu_1230_p4;
wire   [10:0] trunc_ln946_fu_1050_p1;
wire   [10:0] sub_ln969_fu_1252_p2;
wire   [0:0] p_Result_s_fu_1244_p3;
wire   [10:0] add_ln968_fu_1258_p2;
wire   [10:0] select_ln968_fu_1264_p3;
wire   [63:0] zext_ln965_fu_1240_p1;
wire   [11:0] tmp_fu_1272_p3;
wire   [63:0] p_Result_315_fu_1280_p5;
wire   [0:0] icmp_ln938_fu_1026_p2;
wire   [63:0] bitcast_ln746_fu_1292_p1;
wire   [63:0] bitcast_ln443_fu_1325_p1;
wire   [10:0] tmp_22_fu_1328_p4;
wire   [51:0] trunc_ln443_fu_1338_p1;
wire   [0:0] icmp_ln443_4_fu_1348_p2;
wire   [0:0] icmp_ln443_fu_1342_p2;
wire   [0:0] tmp_23_fu_585_p2;
wire   [63:0] bitcast_ln456_fu_1374_p1;
wire   [63:0] xor_ln456_fu_1377_p2;
wire   [0:0] tmp_25_fu_590_p2;
wire   [0:0] and_ln443_4_fu_1388_p2;
wire   [63:0] bitcast_ln541_fu_1506_p1;
wire   [63:0] xor_ln541_fu_1510_p2;
wire   [63:0] bitcast_ln541_4_fu_1516_p1;
wire   [63:0] select_ln540_fu_1520_p3;
wire    ap_block_pp0_stage0_00001;
wire    ap_CS_fsm_state39;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state39_blk;
reg    ap_block_pp0;
reg    ap_predicate_op76_load_state3;
reg    ap_enable_operation_76;
reg    ap_enable_state3_pp0_iter0_stage0;
reg    ap_predicate_op100_load_state4;
reg    ap_enable_operation_100;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_predicate_op108_store_state4;
reg    ap_enable_operation_108;
reg    ap_predicate_op78_load_state3;
reg    ap_enable_operation_78;
reg    ap_predicate_op101_load_state4;
reg    ap_enable_operation_101;
reg    ap_predicate_op103_store_state4;
reg    ap_enable_operation_103;
reg    ap_predicate_op80_load_state3;
reg    ap_enable_operation_80;
reg    ap_predicate_op105_load_state4;
reg    ap_enable_operation_105;
reg    ap_predicate_op82_load_state3;
reg    ap_enable_operation_82;
reg    ap_predicate_op106_load_state4;
reg    ap_enable_operation_106;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1740;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 grp_seedInitialization_fu_432_ap_start_reg = 1'b0;
end

TOP_AWGN_rngMT19937ICN_uniformRNG_mt_odd_0_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
rngMT19937ICN_uniformRNG_mt_odd_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rngMT19937ICN_uniformRNG_mt_odd_0_V_address0),
    .ce0(rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0),
    .we0(rngMT19937ICN_uniformRNG_mt_odd_0_V_we0),
    .d0(rngMT19937ICN_uniformRNG_mt_odd_0_V_d0),
    .q0(rngMT19937ICN_uniformRNG_mt_odd_0_V_q0),
    .address1(rngMT19937ICN_uniformRNG_mt_odd_0_V_address1),
    .ce1(rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1),
    .q1(rngMT19937ICN_uniformRNG_mt_odd_0_V_q1)
);

TOP_AWGN_rngMT19937ICN_1_RAM_AUTO_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
rngMT19937ICN_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_seedInitialization_fu_432_this_mt_odd_1_address0),
    .ce0(grp_seedInitialization_fu_432_this_mt_odd_1_ce0),
    .we0(grp_seedInitialization_fu_432_this_mt_odd_1_we0),
    .d0(grp_seedInitialization_fu_432_this_mt_odd_1_d0)
);

TOP_AWGN_rngMT19937ICN_uniformRNG_mt_odd_0_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
rngMT19937ICN_uniformRNG_mt_even_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rngMT19937ICN_uniformRNG_mt_even_0_V_address0),
    .ce0(rngMT19937ICN_uniformRNG_mt_even_0_V_ce0),
    .we0(rngMT19937ICN_uniformRNG_mt_even_0_V_we0),
    .d0(rngMT19937ICN_uniformRNG_mt_even_0_V_d0),
    .q0(rngMT19937ICN_uniformRNG_mt_even_0_V_q0),
    .address1(rngMT19937ICN_uniformRNG_mt_even_0_V_address1),
    .ce1(rngMT19937ICN_uniformRNG_mt_even_0_V_ce1),
    .q1(rngMT19937ICN_uniformRNG_mt_even_0_V_q1)
);

TOP_AWGN_rngMT19937ICN_1_RAM_AUTO_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
rngMT19937ICN_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_seedInitialization_fu_432_this_mt_even_1_address0),
    .ce0(grp_seedInitialization_fu_432_this_mt_even_1_ce0),
    .we0(grp_seedInitialization_fu_432_this_mt_even_1_we0),
    .d0(grp_seedInitialization_fu_432_this_mt_even_1_d0)
);

TOP_seedInitialization grp_seedInitialization_fu_432(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_seedInitialization_fu_432_ap_start),
    .ap_done(grp_seedInitialization_fu_432_ap_done),
    .ap_idle(grp_seedInitialization_fu_432_ap_idle),
    .ap_ready(grp_seedInitialization_fu_432_ap_ready),
    .this_mt_odd_0_address0(grp_seedInitialization_fu_432_this_mt_odd_0_address0),
    .this_mt_odd_0_ce0(grp_seedInitialization_fu_432_this_mt_odd_0_ce0),
    .this_mt_odd_0_we0(grp_seedInitialization_fu_432_this_mt_odd_0_we0),
    .this_mt_odd_0_d0(grp_seedInitialization_fu_432_this_mt_odd_0_d0),
    .this_mt_odd_0_q0(rngMT19937ICN_uniformRNG_mt_odd_0_V_q0),
    .this_mt_odd_0_address1(grp_seedInitialization_fu_432_this_mt_odd_0_address1),
    .this_mt_odd_0_ce1(grp_seedInitialization_fu_432_this_mt_odd_0_ce1),
    .this_mt_odd_0_q1(rngMT19937ICN_uniformRNG_mt_odd_0_V_q1),
    .this_mt_odd_1_address0(grp_seedInitialization_fu_432_this_mt_odd_1_address0),
    .this_mt_odd_1_ce0(grp_seedInitialization_fu_432_this_mt_odd_1_ce0),
    .this_mt_odd_1_we0(grp_seedInitialization_fu_432_this_mt_odd_1_we0),
    .this_mt_odd_1_d0(grp_seedInitialization_fu_432_this_mt_odd_1_d0),
    .this_mt_even_0_address0(grp_seedInitialization_fu_432_this_mt_even_0_address0),
    .this_mt_even_0_ce0(grp_seedInitialization_fu_432_this_mt_even_0_ce0),
    .this_mt_even_0_we0(grp_seedInitialization_fu_432_this_mt_even_0_we0),
    .this_mt_even_0_d0(grp_seedInitialization_fu_432_this_mt_even_0_d0),
    .this_mt_even_0_q0(rngMT19937ICN_uniformRNG_mt_even_0_V_q0),
    .this_mt_even_1_address0(grp_seedInitialization_fu_432_this_mt_even_1_address0),
    .this_mt_even_1_ce0(grp_seedInitialization_fu_432_this_mt_even_1_ce0),
    .this_mt_even_1_we0(grp_seedInitialization_fu_432_this_mt_even_1_we0),
    .this_mt_even_1_d0(grp_seedInitialization_fu_432_this_mt_even_1_d0),
    .seed(5'd20),
    .ap_return_0(grp_seedInitialization_fu_432_ap_return_0),
    .ap_return_1(grp_seedInitialization_fu_432_ap_return_1),
    .ap_return_2(grp_seedInitialization_fu_432_ap_return_2),
    .ap_return_3(grp_seedInitialization_fu_432_ap_return_3)
);

TOP_dcmp_64ns_64ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_1_no_dsp_1_U195(
    .din0(tmp_uniform_reg_1607),
    .din1(64'd4582646808030102946),
    .opcode(5'd4),
    .dout(tmp_23_fu_585_p2)
);

TOP_dcmp_64ns_64ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_1_no_dsp_1_U196(
    .din0(tmp_uniform_reg_1607_pp0_iter9_reg),
    .din1(64'd4606963994218089939),
    .opcode(5'd2),
    .dout(tmp_25_fu_590_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((grp_seedInitialization_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state4)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end else if (((grp_seedInitialization_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter35 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_seedInitialization_fu_432_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_seedInitialization_fu_432_ap_start_reg <= 1'b1;
        end else if ((grp_seedInitialization_fu_432_ap_ready == 1'b1)) begin
            grp_seedInitialization_fu_432_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_300 <= 4'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_fu_650_p2 == 1'd0))) begin
        j_fu_300 <= add_ln17_fu_656_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_seedInitialization_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        lhs_V_fu_292 <= grp_seedInitialization_fu_432_ap_return_3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_1579 == 1'd0))) begin
        lhs_V_fu_292 <= ap_phi_mux_p_0_0_0604_phi_fu_424_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_seedInitialization_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_Val2_172_fu_304 <= grp_seedInitialization_fu_432_ap_return_1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_1579 == 1'd0))) begin
        p_Val2_172_fu_304 <= rngMT19937ICN_uniformRNG_x_k_p_2_V_1_fu_288;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_seedInitialization_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_Val2_s_fu_296 <= grp_seedInitialization_fu_432_ap_return_0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_1579 == 1'd0))) begin
        p_Val2_s_fu_296 <= p_Val2_172_fu_304;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_seedInitialization_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        rngMT19937ICN_uniformRNG_x_k_p_2_V_1_fu_288 <= grp_seedInitialization_fu_432_ap_return_2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_1579 == 1'd0))) begin
        rngMT19937ICN_uniformRNG_x_k_p_2_V_1_fu_288 <= ap_phi_mux_p_0_0_0616_phi_fu_413_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln443_reg_1622 <= and_ln443_fu_1360_p2;
        and_ln443_reg_1622_pp0_iter10_reg <= and_ln443_reg_1622_pp0_iter9_reg;
        and_ln443_reg_1622_pp0_iter11_reg <= and_ln443_reg_1622_pp0_iter10_reg;
        and_ln443_reg_1622_pp0_iter12_reg <= and_ln443_reg_1622_pp0_iter11_reg;
        and_ln443_reg_1622_pp0_iter13_reg <= and_ln443_reg_1622_pp0_iter12_reg;
        and_ln443_reg_1622_pp0_iter14_reg <= and_ln443_reg_1622_pp0_iter13_reg;
        and_ln443_reg_1622_pp0_iter15_reg <= and_ln443_reg_1622_pp0_iter14_reg;
        and_ln443_reg_1622_pp0_iter16_reg <= and_ln443_reg_1622_pp0_iter15_reg;
        and_ln443_reg_1622_pp0_iter17_reg <= and_ln443_reg_1622_pp0_iter16_reg;
        and_ln443_reg_1622_pp0_iter18_reg <= and_ln443_reg_1622_pp0_iter17_reg;
        and_ln443_reg_1622_pp0_iter19_reg <= and_ln443_reg_1622_pp0_iter18_reg;
        and_ln443_reg_1622_pp0_iter20_reg <= and_ln443_reg_1622_pp0_iter19_reg;
        and_ln443_reg_1622_pp0_iter21_reg <= and_ln443_reg_1622_pp0_iter20_reg;
        and_ln443_reg_1622_pp0_iter22_reg <= and_ln443_reg_1622_pp0_iter21_reg;
        and_ln443_reg_1622_pp0_iter23_reg <= and_ln443_reg_1622_pp0_iter22_reg;
        and_ln443_reg_1622_pp0_iter24_reg <= and_ln443_reg_1622_pp0_iter23_reg;
        and_ln443_reg_1622_pp0_iter25_reg <= and_ln443_reg_1622_pp0_iter24_reg;
        and_ln443_reg_1622_pp0_iter26_reg <= and_ln443_reg_1622_pp0_iter25_reg;
        and_ln443_reg_1622_pp0_iter27_reg <= and_ln443_reg_1622_pp0_iter26_reg;
        and_ln443_reg_1622_pp0_iter3_reg <= and_ln443_reg_1622;
        and_ln443_reg_1622_pp0_iter4_reg <= and_ln443_reg_1622_pp0_iter3_reg;
        and_ln443_reg_1622_pp0_iter5_reg <= and_ln443_reg_1622_pp0_iter4_reg;
        and_ln443_reg_1622_pp0_iter6_reg <= and_ln443_reg_1622_pp0_iter5_reg;
        and_ln443_reg_1622_pp0_iter7_reg <= and_ln443_reg_1622_pp0_iter6_reg;
        and_ln443_reg_1622_pp0_iter8_reg <= and_ln443_reg_1622_pp0_iter7_reg;
        and_ln443_reg_1622_pp0_iter9_reg <= and_ln443_reg_1622_pp0_iter8_reg;
        div_reg_1864 <= grp_fu_1085_p_dout0;
        f1_1_reg_1838 <= grp_fu_1129_p_dout0;
        f1_4_reg_1844 <= f1_4_fu_1500_p3;
        f2_10_reg_1849 <= grp_fu_1133_p_dout0;
        f2_reg_1792 <= grp_fu_1117_p_dout0;
        f2_reg_1792_pp0_iter19_reg <= f2_reg_1792;
        icmp_ln17_reg_1579_pp0_iter10_reg <= icmp_ln17_reg_1579_pp0_iter9_reg;
        icmp_ln17_reg_1579_pp0_iter11_reg <= icmp_ln17_reg_1579_pp0_iter10_reg;
        icmp_ln17_reg_1579_pp0_iter12_reg <= icmp_ln17_reg_1579_pp0_iter11_reg;
        icmp_ln17_reg_1579_pp0_iter13_reg <= icmp_ln17_reg_1579_pp0_iter12_reg;
        icmp_ln17_reg_1579_pp0_iter14_reg <= icmp_ln17_reg_1579_pp0_iter13_reg;
        icmp_ln17_reg_1579_pp0_iter15_reg <= icmp_ln17_reg_1579_pp0_iter14_reg;
        icmp_ln17_reg_1579_pp0_iter16_reg <= icmp_ln17_reg_1579_pp0_iter15_reg;
        icmp_ln17_reg_1579_pp0_iter17_reg <= icmp_ln17_reg_1579_pp0_iter16_reg;
        icmp_ln17_reg_1579_pp0_iter18_reg <= icmp_ln17_reg_1579_pp0_iter17_reg;
        icmp_ln17_reg_1579_pp0_iter19_reg <= icmp_ln17_reg_1579_pp0_iter18_reg;
        icmp_ln17_reg_1579_pp0_iter20_reg <= icmp_ln17_reg_1579_pp0_iter19_reg;
        icmp_ln17_reg_1579_pp0_iter21_reg <= icmp_ln17_reg_1579_pp0_iter20_reg;
        icmp_ln17_reg_1579_pp0_iter22_reg <= icmp_ln17_reg_1579_pp0_iter21_reg;
        icmp_ln17_reg_1579_pp0_iter23_reg <= icmp_ln17_reg_1579_pp0_iter22_reg;
        icmp_ln17_reg_1579_pp0_iter24_reg <= icmp_ln17_reg_1579_pp0_iter23_reg;
        icmp_ln17_reg_1579_pp0_iter25_reg <= icmp_ln17_reg_1579_pp0_iter24_reg;
        icmp_ln17_reg_1579_pp0_iter26_reg <= icmp_ln17_reg_1579_pp0_iter25_reg;
        icmp_ln17_reg_1579_pp0_iter27_reg <= icmp_ln17_reg_1579_pp0_iter26_reg;
        icmp_ln17_reg_1579_pp0_iter28_reg <= icmp_ln17_reg_1579_pp0_iter27_reg;
        icmp_ln17_reg_1579_pp0_iter29_reg <= icmp_ln17_reg_1579_pp0_iter28_reg;
        icmp_ln17_reg_1579_pp0_iter2_reg <= icmp_ln17_reg_1579_pp0_iter1_reg;
        icmp_ln17_reg_1579_pp0_iter30_reg <= icmp_ln17_reg_1579_pp0_iter29_reg;
        icmp_ln17_reg_1579_pp0_iter31_reg <= icmp_ln17_reg_1579_pp0_iter30_reg;
        icmp_ln17_reg_1579_pp0_iter32_reg <= icmp_ln17_reg_1579_pp0_iter31_reg;
        icmp_ln17_reg_1579_pp0_iter3_reg <= icmp_ln17_reg_1579_pp0_iter2_reg;
        icmp_ln17_reg_1579_pp0_iter4_reg <= icmp_ln17_reg_1579_pp0_iter3_reg;
        icmp_ln17_reg_1579_pp0_iter5_reg <= icmp_ln17_reg_1579_pp0_iter4_reg;
        icmp_ln17_reg_1579_pp0_iter6_reg <= icmp_ln17_reg_1579_pp0_iter5_reg;
        icmp_ln17_reg_1579_pp0_iter7_reg <= icmp_ln17_reg_1579_pp0_iter6_reg;
        icmp_ln17_reg_1579_pp0_iter8_reg <= icmp_ln17_reg_1579_pp0_iter7_reg;
        icmp_ln17_reg_1579_pp0_iter9_reg <= icmp_ln17_reg_1579_pp0_iter8_reg;
        j_6_reg_1573_pp0_iter10_reg <= j_6_reg_1573_pp0_iter9_reg;
        j_6_reg_1573_pp0_iter11_reg <= j_6_reg_1573_pp0_iter10_reg;
        j_6_reg_1573_pp0_iter12_reg <= j_6_reg_1573_pp0_iter11_reg;
        j_6_reg_1573_pp0_iter13_reg <= j_6_reg_1573_pp0_iter12_reg;
        j_6_reg_1573_pp0_iter14_reg <= j_6_reg_1573_pp0_iter13_reg;
        j_6_reg_1573_pp0_iter15_reg <= j_6_reg_1573_pp0_iter14_reg;
        j_6_reg_1573_pp0_iter16_reg <= j_6_reg_1573_pp0_iter15_reg;
        j_6_reg_1573_pp0_iter17_reg <= j_6_reg_1573_pp0_iter16_reg;
        j_6_reg_1573_pp0_iter18_reg <= j_6_reg_1573_pp0_iter17_reg;
        j_6_reg_1573_pp0_iter19_reg <= j_6_reg_1573_pp0_iter18_reg;
        j_6_reg_1573_pp0_iter20_reg <= j_6_reg_1573_pp0_iter19_reg;
        j_6_reg_1573_pp0_iter21_reg <= j_6_reg_1573_pp0_iter20_reg;
        j_6_reg_1573_pp0_iter22_reg <= j_6_reg_1573_pp0_iter21_reg;
        j_6_reg_1573_pp0_iter23_reg <= j_6_reg_1573_pp0_iter22_reg;
        j_6_reg_1573_pp0_iter24_reg <= j_6_reg_1573_pp0_iter23_reg;
        j_6_reg_1573_pp0_iter25_reg <= j_6_reg_1573_pp0_iter24_reg;
        j_6_reg_1573_pp0_iter26_reg <= j_6_reg_1573_pp0_iter25_reg;
        j_6_reg_1573_pp0_iter27_reg <= j_6_reg_1573_pp0_iter26_reg;
        j_6_reg_1573_pp0_iter28_reg <= j_6_reg_1573_pp0_iter27_reg;
        j_6_reg_1573_pp0_iter29_reg <= j_6_reg_1573_pp0_iter28_reg;
        j_6_reg_1573_pp0_iter2_reg <= j_6_reg_1573_pp0_iter1_reg;
        j_6_reg_1573_pp0_iter30_reg <= j_6_reg_1573_pp0_iter29_reg;
        j_6_reg_1573_pp0_iter31_reg <= j_6_reg_1573_pp0_iter30_reg;
        j_6_reg_1573_pp0_iter32_reg <= j_6_reg_1573_pp0_iter31_reg;
        j_6_reg_1573_pp0_iter3_reg <= j_6_reg_1573_pp0_iter2_reg;
        j_6_reg_1573_pp0_iter4_reg <= j_6_reg_1573_pp0_iter3_reg;
        j_6_reg_1573_pp0_iter5_reg <= j_6_reg_1573_pp0_iter4_reg;
        j_6_reg_1573_pp0_iter6_reg <= j_6_reg_1573_pp0_iter5_reg;
        j_6_reg_1573_pp0_iter7_reg <= j_6_reg_1573_pp0_iter6_reg;
        j_6_reg_1573_pp0_iter8_reg <= j_6_reg_1573_pp0_iter7_reg;
        j_6_reg_1573_pp0_iter9_reg <= j_6_reg_1573_pp0_iter8_reg;
        j_cast_reg_1859_pp0_iter34_reg[3 : 0] <= j_cast_reg_1859[3 : 0];
        or_ln443_4_reg_1648 <= or_ln443_4_fu_1393_p2;
        or_ln443_4_reg_1648_pp0_iter11_reg <= or_ln443_4_reg_1648;
        or_ln443_4_reg_1648_pp0_iter12_reg <= or_ln443_4_reg_1648_pp0_iter11_reg;
        or_ln443_4_reg_1648_pp0_iter13_reg <= or_ln443_4_reg_1648_pp0_iter12_reg;
        or_ln443_4_reg_1648_pp0_iter14_reg <= or_ln443_4_reg_1648_pp0_iter13_reg;
        or_ln443_4_reg_1648_pp0_iter15_reg <= or_ln443_4_reg_1648_pp0_iter14_reg;
        or_ln443_4_reg_1648_pp0_iter16_reg <= or_ln443_4_reg_1648_pp0_iter15_reg;
        or_ln443_4_reg_1648_pp0_iter17_reg <= or_ln443_4_reg_1648_pp0_iter16_reg;
        or_ln443_4_reg_1648_pp0_iter18_reg <= or_ln443_4_reg_1648_pp0_iter17_reg;
        or_ln443_4_reg_1648_pp0_iter19_reg <= or_ln443_4_reg_1648_pp0_iter18_reg;
        or_ln443_4_reg_1648_pp0_iter20_reg <= or_ln443_4_reg_1648_pp0_iter19_reg;
        or_ln443_4_reg_1648_pp0_iter21_reg <= or_ln443_4_reg_1648_pp0_iter20_reg;
        or_ln443_4_reg_1648_pp0_iter22_reg <= or_ln443_4_reg_1648_pp0_iter21_reg;
        or_ln443_4_reg_1648_pp0_iter23_reg <= or_ln443_4_reg_1648_pp0_iter22_reg;
        or_ln443_4_reg_1648_pp0_iter24_reg <= or_ln443_4_reg_1648_pp0_iter23_reg;
        or_ln443_4_reg_1648_pp0_iter25_reg <= or_ln443_4_reg_1648_pp0_iter24_reg;
        or_ln443_4_reg_1648_pp0_iter26_reg <= or_ln443_4_reg_1648_pp0_iter25_reg;
        or_ln443_4_reg_1648_pp0_iter27_reg <= or_ln443_4_reg_1648_pp0_iter26_reg;
        or_ln443_reg_1617 <= or_ln443_fu_1354_p2;
        or_ln443_reg_1617_pp0_iter3_reg <= or_ln443_reg_1617;
        or_ln443_reg_1617_pp0_iter4_reg <= or_ln443_reg_1617_pp0_iter3_reg;
        or_ln443_reg_1617_pp0_iter5_reg <= or_ln443_reg_1617_pp0_iter4_reg;
        or_ln443_reg_1617_pp0_iter6_reg <= or_ln443_reg_1617_pp0_iter5_reg;
        or_ln443_reg_1617_pp0_iter7_reg <= or_ln443_reg_1617_pp0_iter6_reg;
        or_ln443_reg_1617_pp0_iter8_reg <= or_ln443_reg_1617_pp0_iter7_reg;
        or_ln443_reg_1617_pp0_iter9_reg <= or_ln443_reg_1617_pp0_iter8_reg;
        r_21_reg_1683 <= r_21_fu_1405_p3;
        r_21_reg_1683_pp0_iter13_reg <= r_21_reg_1683;
        r_21_reg_1683_pp0_iter14_reg <= r_21_reg_1683_pp0_iter13_reg;
        r_21_reg_1683_pp0_iter15_reg <= r_21_reg_1683_pp0_iter14_reg;
        r_21_reg_1683_pp0_iter16_reg <= r_21_reg_1683_pp0_iter15_reg;
        r_21_reg_1683_pp0_iter17_reg <= r_21_reg_1683_pp0_iter16_reg;
        r_21_reg_1683_pp0_iter18_reg <= r_21_reg_1683_pp0_iter17_reg;
        r_21_reg_1683_pp0_iter19_reg <= r_21_reg_1683_pp0_iter18_reg;
        result_reg_1854 <= result_fu_1527_p3;
        t19_reg_1833 <= grp_fu_1181_p_dout0;
        t2_reg_1638 <= grp_fu_1137_p_dout0;
        tmp_uniform_reg_1607_pp0_iter2_reg <= tmp_uniform_reg_1607;
        tmp_uniform_reg_1607_pp0_iter3_reg <= tmp_uniform_reg_1607_pp0_iter2_reg;
        tmp_uniform_reg_1607_pp0_iter4_reg <= tmp_uniform_reg_1607_pp0_iter3_reg;
        tmp_uniform_reg_1607_pp0_iter5_reg <= tmp_uniform_reg_1607_pp0_iter4_reg;
        tmp_uniform_reg_1607_pp0_iter6_reg <= tmp_uniform_reg_1607_pp0_iter5_reg;
        tmp_uniform_reg_1607_pp0_iter7_reg <= tmp_uniform_reg_1607_pp0_iter6_reg;
        tmp_uniform_reg_1607_pp0_iter8_reg <= tmp_uniform_reg_1607_pp0_iter7_reg;
        tmp_uniform_reg_1607_pp0_iter9_reg <= tmp_uniform_reg_1607_pp0_iter8_reg;
        z_10_reg_1673 <= grp_fu_1189_p_dout0;
        z_9_reg_1678_pp0_iter12_reg <= z_9_reg_1678;
        z_9_reg_1678_pp0_iter13_reg <= z_9_reg_1678_pp0_iter12_reg;
        z_9_reg_1678_pp0_iter14_reg <= z_9_reg_1678_pp0_iter13_reg;
        z_9_reg_1678_pp0_iter15_reg <= z_9_reg_1678_pp0_iter14_reg;
        z_9_reg_1678_pp0_iter16_reg <= z_9_reg_1678_pp0_iter15_reg;
        z_9_reg_1678_pp0_iter17_reg <= z_9_reg_1678_pp0_iter16_reg;
        z_9_reg_1678_pp0_iter18_reg <= z_9_reg_1678_pp0_iter17_reg;
        z_9_reg_1678_pp0_iter19_reg <= z_9_reg_1678_pp0_iter18_reg;
        z_9_reg_1678_pp0_iter20_reg <= z_9_reg_1678_pp0_iter19_reg;
        z_9_reg_1678_pp0_iter21_reg <= z_9_reg_1678_pp0_iter20_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln17_reg_1579 <= icmp_ln17_fu_650_p2;
        icmp_ln17_reg_1579_pp0_iter1_reg <= icmp_ln17_reg_1579;
        j_6_reg_1573 <= j_fu_300;
        j_6_reg_1573_pp0_iter1_reg <= j_6_reg_1573;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln17_reg_1579_pp0_iter32_reg == 1'd0))) begin
        j_cast_reg_1859[3 : 0] <= j_cast_fu_1534_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_1579 == 1'd0))) begin
        tmp_uniform_reg_1607 <= tmp_uniform_fu_1296_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_fu_650_p2 == 1'd0))) begin
        trunc_ln229_reg_1583 <= trunc_ln229_fu_666_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln443_4_reg_1648 == 1'd0))) begin
        z_9_reg_1678 <= z_9_fu_1398_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_seedInitialization_fu_432_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_fu_650_p2 == 1'd1))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln17_reg_1579 == 1'd0)) begin
        if ((trunc_ln229_reg_1583 == 1'd1)) begin
            ap_phi_mux_p_0_0_0604_phi_fu_424_p4 = rngMT19937ICN_uniformRNG_mt_odd_0_V_q1;
        end else if ((trunc_ln229_reg_1583 == 1'd0)) begin
            ap_phi_mux_p_0_0_0604_phi_fu_424_p4 = rngMT19937ICN_uniformRNG_mt_even_0_V_q1;
        end else begin
            ap_phi_mux_p_0_0_0604_phi_fu_424_p4 = ap_phi_reg_pp0_iter1_p_0_0_0604_reg_421;
        end
    end else begin
        ap_phi_mux_p_0_0_0604_phi_fu_424_p4 = ap_phi_reg_pp0_iter1_p_0_0_0604_reg_421;
    end
end

always @ (*) begin
    if ((icmp_ln17_reg_1579 == 1'd0)) begin
        if ((trunc_ln229_reg_1583 == 1'd1)) begin
            ap_phi_mux_p_0_0_0616_phi_fu_413_p4 = rngMT19937ICN_uniformRNG_mt_even_0_V_q1;
        end else if ((trunc_ln229_reg_1583 == 1'd0)) begin
            ap_phi_mux_p_0_0_0616_phi_fu_413_p4 = rngMT19937ICN_uniformRNG_mt_odd_0_V_q1;
        end else begin
            ap_phi_mux_p_0_0_0616_phi_fu_413_p4 = ap_phi_reg_pp0_iter1_p_0_0_0616_reg_410;
        end
    end else begin
        ap_phi_mux_p_0_0_0616_phi_fu_413_p4 = ap_phi_reg_pp0_iter1_p_0_0_0616_reg_410;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter33 == 1'b1))) begin
        din_ce0 = 1'b1;
    end else begin
        din_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        dout_ce0 = 1'b1;
    end else begin
        dout_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        dout_we0 = 1'b1;
    end else begin
        dout_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_address0 = zext_ln587_9_fu_805_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_address0 = grp_seedInitialization_fu_432_this_mt_even_0_address0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1740)) begin
        if ((trunc_ln229_fu_666_p1 == 1'd1)) begin
            rngMT19937ICN_uniformRNG_mt_even_0_V_address1 = zext_ln587_fu_702_p1;
        end else if ((trunc_ln229_fu_666_p1 == 1'd0)) begin
            rngMT19937ICN_uniformRNG_mt_even_0_V_address1 = zext_ln587_8_fu_712_p1;
        end else begin
            rngMT19937ICN_uniformRNG_mt_even_0_V_address1 = 'bx;
        end
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce0 = grp_seedInitialization_fu_432_this_mt_even_0_ce0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln229_fu_666_p1 == 1'd1) & (icmp_ln17_fu_650_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln229_fu_666_p1 == 1'd0) & (icmp_ln17_fu_650_p2 == 1'd0)))) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce1 = 1'b1;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_d0 = ret_42_fu_780_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_d0 = grp_seedInitialization_fu_432_this_mt_even_0_d0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln229_reg_1583 == 1'd0) & (icmp_ln17_reg_1579 == 1'd0))) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_we0 = grp_seedInitialization_fu_432_this_mt_even_0_we0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address0 = zext_ln587_9_fu_805_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address0 = grp_seedInitialization_fu_432_this_mt_odd_0_address0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln229_fu_666_p1 == 1'd1) & (icmp_ln17_fu_650_p2 == 1'd0))) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address1 = zext_ln587_8_fu_712_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln229_fu_666_p1 == 1'd0) & (icmp_ln17_fu_650_p2 == 1'd0))) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address1 = zext_ln587_fu_702_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address1 = grp_seedInitialization_fu_432_this_mt_odd_0_address1;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0 = grp_seedInitialization_fu_432_this_mt_odd_0_ce0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln229_fu_666_p1 == 1'd1) & (icmp_ln17_fu_650_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln229_fu_666_p1 == 1'd0) & (icmp_ln17_fu_650_p2 == 1'd0)))) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1 = grp_seedInitialization_fu_432_this_mt_odd_0_ce1;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_d0 = ret_42_fu_780_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_d0 = grp_seedInitialization_fu_432_this_mt_odd_0_d0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln229_reg_1583 == 1'd1) & (icmp_ln17_reg_1579 == 1'd0))) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_we0 = grp_seedInitialization_fu_432_this_mt_odd_0_we0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_seedInitialization_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter35 == 1'b1) & (ap_enable_reg_pp0_iter34 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter35 == 1'b1) & (ap_enable_reg_pp0_iter34 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln17_fu_656_p2 = (j_fu_300 + 4'd1);

assign add_ln961_fu_1188_p2 = ($signed(sub_ln947_fu_1054_p2) + $signed(32'd4294967242));

assign add_ln968_fu_1258_p2 = (sub_ln969_fu_1252_p2 + 11'd1);

assign addr_head_p_3_V_fu_670_p2 = (j_fu_300 + 4'd3);

assign addr_head_p_m_p_1_V_fu_676_p2 = ($signed(p_cast13_fu_662_p1) + $signed(8'd142));

assign and_ln443_4_fu_1388_p2 = (tmp_25_fu_590_p2 & or_ln443_reg_1617_pp0_iter9_reg);

assign and_ln443_fu_1360_p2 = (tmp_23_fu_585_p2 & or_ln443_fu_1354_p2);

assign and_ln952_13_fu_1158_p2 = (xor_ln952_fu_1138_p2 & p_Result_314_fu_1144_p3);

assign and_ln952_fu_1118_p2 = (pre_result_V_fu_1020_p2 & or_ln952_10_fu_1112_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1740 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_fu_650_p2 == 1'd0));
end

always @ (*) begin
    ap_enable_operation_100 = (ap_predicate_op100_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_101 = (ap_predicate_op101_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_103 = (ap_predicate_op103_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_105 = (ap_predicate_op105_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_106 = (ap_predicate_op106_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_108 = (ap_predicate_op108_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_76 = (ap_predicate_op76_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_78 = (ap_predicate_op78_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_80 = (ap_predicate_op80_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_82 = (ap_predicate_op82_load_state3 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state3_pp0_iter0_stage0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_phi_reg_pp0_iter1_p_0_0_0604_reg_421 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_0616_reg_410 = 'bx;

always @ (*) begin
    ap_predicate_op100_load_state4 = ((trunc_ln229_reg_1583 == 1'd0) & (icmp_ln17_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op101_load_state4 = ((trunc_ln229_reg_1583 == 1'd0) & (icmp_ln17_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op103_store_state4 = ((trunc_ln229_reg_1583 == 1'd0) & (icmp_ln17_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op105_load_state4 = ((trunc_ln229_reg_1583 == 1'd1) & (icmp_ln17_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op106_load_state4 = ((trunc_ln229_reg_1583 == 1'd1) & (icmp_ln17_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op108_store_state4 = ((trunc_ln229_reg_1583 == 1'd1) & (icmp_ln17_reg_1579 == 1'd0));
end

always @ (*) begin
    ap_predicate_op76_load_state3 = ((trunc_ln229_fu_666_p1 == 1'd0) & (icmp_ln17_fu_650_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op78_load_state3 = ((trunc_ln229_fu_666_p1 == 1'd0) & (icmp_ln17_fu_650_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op80_load_state3 = ((trunc_ln229_fu_666_p1 == 1'd1) & (icmp_ln17_fu_650_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op82_load_state3 = ((trunc_ln229_fu_666_p1 == 1'd1) & (icmp_ln17_fu_650_p2 == 1'd0));
end

assign bitcast_ln443_fu_1325_p1 = tmp_uniform_reg_1607;

assign bitcast_ln456_fu_1374_p1 = t2_reg_1638;

assign bitcast_ln541_4_fu_1516_p1 = xor_ln541_fu_1510_p2;

assign bitcast_ln541_fu_1506_p1 = grp_fu_1081_p_dout0;

assign bitcast_ln746_fu_1292_p1 = p_Result_315_fu_1280_p5;

assign din_address0 = j_cast_fu_1534_p1;

assign dout_address0 = j_cast_reg_1859_pp0_iter34_reg;

assign dout_d0 = grp_fu_1197_p_dout0;

assign f1_4_fu_1500_p3 = ((or_ln443_4_reg_1648_pp0_iter22_reg[0:0] == 1'b1) ? f1_1_reg_1838 : grp_fu_1185_p_dout0);

assign f2_9_fu_1485_p3 = ((or_ln443_4_reg_1648_pp0_iter19_reg[0:0] == 1'b1) ? f2_reg_1792_pp0_iter19_reg : grp_fu_1125_p_dout0);

assign grp_fu_1081_p_ce = 1'b1;

assign grp_fu_1081_p_din0 = f1_4_reg_1844;

assign grp_fu_1081_p_din1 = f2_10_reg_1849;

assign grp_fu_1085_p_ce = 1'b1;

assign grp_fu_1085_p_din0 = result_reg_1854;

assign grp_fu_1085_p_din1 = 64'd4616721195882509480;

assign grp_fu_1089_p_ce = 1'b1;

assign grp_fu_1089_p_din0 = 64'd4607182418800017408;

assign grp_fu_1089_p_din1 = tmp_uniform_fu_1296_p3;

assign grp_fu_1089_p_opcode = 2'd1;

assign grp_fu_1093_p_ce = 1'b1;

assign grp_fu_1093_p_din0 = tmp_uniform_reg_1607_pp0_iter9_reg;

assign grp_fu_1093_p_din1 = 64'd13826050856027422720;

assign grp_fu_1093_p_opcode = 2'd0;

assign grp_fu_1097_p_ce = 1'b1;

assign grp_fu_1097_p_din0 = grp_fu_1145_p_dout0;

assign grp_fu_1097_p_din1 = p2_fu_1429_p3;

assign grp_fu_1097_p_opcode = 2'd0;

assign grp_fu_1101_p_ce = 1'b1;

assign grp_fu_1101_p_din0 = grp_fu_1149_p_dout0;

assign grp_fu_1101_p_din1 = q2_fu_1437_p3;

assign grp_fu_1101_p_opcode = 2'd0;

assign grp_fu_1105_p_ce = 1'b1;

assign grp_fu_1105_p_din0 = grp_fu_1153_p_dout0;

assign grp_fu_1105_p_din1 = p3_fu_1445_p3;

assign grp_fu_1105_p_opcode = 2'd0;

assign grp_fu_1109_p_ce = 1'b1;

assign grp_fu_1109_p_din0 = grp_fu_1157_p_dout0;

assign grp_fu_1109_p_din1 = q3_fu_1453_p3;

assign grp_fu_1109_p_opcode = 2'd0;

assign grp_fu_1113_p_ce = 1'b1;

assign grp_fu_1113_p_din0 = grp_fu_1161_p_dout0;

assign grp_fu_1113_p_din1 = p4_fu_1461_p3;

assign grp_fu_1113_p_opcode = 2'd0;

assign grp_fu_1117_p_ce = 1'b1;

assign grp_fu_1117_p_din0 = grp_fu_1165_p_dout0;

assign grp_fu_1117_p_din1 = q4_fu_1469_p3;

assign grp_fu_1117_p_opcode = 2'd0;

assign grp_fu_1121_p_ce = 1'b1;

assign grp_fu_1121_p_din0 = grp_fu_1169_p_dout0;

assign grp_fu_1121_p_din1 = p5_fu_1477_p3;

assign grp_fu_1121_p_opcode = 2'd0;

assign grp_fu_1125_p_ce = 1'b1;

assign grp_fu_1125_p_din0 = grp_fu_1173_p_dout0;

assign grp_fu_1125_p_din1 = 64'd13847038013971134502;

assign grp_fu_1125_p_opcode = 2'd0;

assign grp_fu_1129_p_ce = 1'b1;

assign grp_fu_1129_p_din0 = grp_fu_1177_p_dout0;

assign grp_fu_1129_p_din1 = p6_fu_1492_p3;

assign grp_fu_1129_p_opcode = 2'd0;

assign grp_fu_1133_p_ce = 1'b1;

assign grp_fu_1133_p_din0 = t19_reg_1833;

assign grp_fu_1133_p_din1 = 64'd4607182418800017408;

assign grp_fu_1133_p_opcode = 2'd0;

assign grp_fu_1137_p_ce = 1'b1;

assign grp_fu_1137_p_din0 = grp_fu_1193_p_dout0;

assign grp_fu_1137_p_din1 = 64'd4611686018427387904;

assign grp_fu_1141_p_ce = 1'b1;

assign grp_fu_1141_p_din0 = grp_fu_1093_p_dout0;

assign grp_fu_1141_p_din1 = grp_fu_1093_p_dout0;

assign grp_fu_1145_p_ce = 1'b1;

assign grp_fu_1145_p_din0 = p1_fu_1413_p3;

assign grp_fu_1145_p_din1 = r_21_fu_1405_p3;

assign grp_fu_1149_p_ce = 1'b1;

assign grp_fu_1149_p_din0 = q1_fu_1421_p3;

assign grp_fu_1149_p_din1 = r_21_fu_1405_p3;

assign grp_fu_1153_p_ce = 1'b1;

assign grp_fu_1153_p_din0 = grp_fu_1097_p_dout0;

assign grp_fu_1153_p_din1 = r_21_reg_1683_pp0_iter13_reg;

assign grp_fu_1157_p_ce = 1'b1;

assign grp_fu_1157_p_din0 = grp_fu_1101_p_dout0;

assign grp_fu_1157_p_din1 = r_21_reg_1683_pp0_iter13_reg;

assign grp_fu_1161_p_ce = 1'b1;

assign grp_fu_1161_p_din0 = grp_fu_1105_p_dout0;

assign grp_fu_1161_p_din1 = r_21_reg_1683_pp0_iter15_reg;

assign grp_fu_1165_p_ce = 1'b1;

assign grp_fu_1165_p_din0 = grp_fu_1109_p_dout0;

assign grp_fu_1165_p_din1 = r_21_reg_1683_pp0_iter15_reg;

assign grp_fu_1169_p_ce = 1'b1;

assign grp_fu_1169_p_din0 = grp_fu_1113_p_dout0;

assign grp_fu_1169_p_din1 = r_21_reg_1683_pp0_iter17_reg;

assign grp_fu_1173_p_ce = 1'b1;

assign grp_fu_1173_p_din0 = grp_fu_1117_p_dout0;

assign grp_fu_1173_p_din1 = r_21_reg_1683_pp0_iter17_reg;

assign grp_fu_1177_p_ce = 1'b1;

assign grp_fu_1177_p_din0 = grp_fu_1121_p_dout0;

assign grp_fu_1177_p_din1 = r_21_reg_1683_pp0_iter19_reg;

assign grp_fu_1181_p_ce = 1'b1;

assign grp_fu_1181_p_din0 = f2_9_fu_1485_p3;

assign grp_fu_1181_p_din1 = r_21_reg_1683_pp0_iter19_reg;

assign grp_fu_1185_p_ce = 1'b1;

assign grp_fu_1185_p_din0 = grp_fu_1129_p_dout0;

assign grp_fu_1185_p_din1 = z_9_reg_1678_pp0_iter21_reg;

assign grp_fu_1189_p_ce = 1'b1;

assign grp_fu_1189_p_din0 = 64'd0;

assign grp_fu_1189_p_din1 = t3_fu_1383_p1;

assign grp_fu_1193_p_ce = 1'b1;

assign grp_fu_1193_p_din0 = 64'd0;

assign grp_fu_1193_p_din1 = tmp_472_fu_1366_p3;

assign grp_fu_1197_p_ce = 1'b1;

assign grp_fu_1197_p_din0 = div_reg_1864;

assign grp_fu_1197_p_din1 = din_q0;

assign grp_fu_1197_p_opcode = 2'd0;

assign grp_seedInitialization_fu_432_ap_start = grp_seedInitialization_fu_432_ap_start_reg;

assign icmp_ln17_fu_650_p2 = ((j_fu_300 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln443_4_fu_1348_p2 = ((trunc_ln443_fu_1338_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln443_fu_1342_p2 = ((tmp_22_fu_1328_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln938_fu_1026_p2 = ((zext_ln1691_11_fu_1016_p1 == pre_result_V_53_fu_1000_p2) ? 1'b1 : 1'b0);

assign icmp_ln949_fu_1076_p2 = (($signed(tmp_469_fu_1066_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln952_fu_1124_p2 = ((and_ln952_fu_1118_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln961_fu_1152_p2 = (($signed(lsb_index_fu_1060_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign j_cast_fu_1534_p1 = j_6_reg_1573_pp0_iter32_reg;


always @ (p_Result_313_fu_1032_p4) begin
    if (p_Result_313_fu_1032_p4[0] == 1'b1) begin
        l_fu_1042_p3 = 32'd0;
    end else if (p_Result_313_fu_1032_p4[1] == 1'b1) begin
        l_fu_1042_p3 = 32'd1;
    end else if (p_Result_313_fu_1032_p4[2] == 1'b1) begin
        l_fu_1042_p3 = 32'd2;
    end else if (p_Result_313_fu_1032_p4[3] == 1'b1) begin
        l_fu_1042_p3 = 32'd3;
    end else if (p_Result_313_fu_1032_p4[4] == 1'b1) begin
        l_fu_1042_p3 = 32'd4;
    end else if (p_Result_313_fu_1032_p4[5] == 1'b1) begin
        l_fu_1042_p3 = 32'd5;
    end else if (p_Result_313_fu_1032_p4[6] == 1'b1) begin
        l_fu_1042_p3 = 32'd6;
    end else if (p_Result_313_fu_1032_p4[7] == 1'b1) begin
        l_fu_1042_p3 = 32'd7;
    end else if (p_Result_313_fu_1032_p4[8] == 1'b1) begin
        l_fu_1042_p3 = 32'd8;
    end else if (p_Result_313_fu_1032_p4[9] == 1'b1) begin
        l_fu_1042_p3 = 32'd9;
    end else if (p_Result_313_fu_1032_p4[10] == 1'b1) begin
        l_fu_1042_p3 = 32'd10;
    end else if (p_Result_313_fu_1032_p4[11] == 1'b1) begin
        l_fu_1042_p3 = 32'd11;
    end else if (p_Result_313_fu_1032_p4[12] == 1'b1) begin
        l_fu_1042_p3 = 32'd12;
    end else if (p_Result_313_fu_1032_p4[13] == 1'b1) begin
        l_fu_1042_p3 = 32'd13;
    end else if (p_Result_313_fu_1032_p4[14] == 1'b1) begin
        l_fu_1042_p3 = 32'd14;
    end else if (p_Result_313_fu_1032_p4[15] == 1'b1) begin
        l_fu_1042_p3 = 32'd15;
    end else if (p_Result_313_fu_1032_p4[16] == 1'b1) begin
        l_fu_1042_p3 = 32'd16;
    end else if (p_Result_313_fu_1032_p4[17] == 1'b1) begin
        l_fu_1042_p3 = 32'd17;
    end else if (p_Result_313_fu_1032_p4[18] == 1'b1) begin
        l_fu_1042_p3 = 32'd18;
    end else if (p_Result_313_fu_1032_p4[19] == 1'b1) begin
        l_fu_1042_p3 = 32'd19;
    end else if (p_Result_313_fu_1032_p4[20] == 1'b1) begin
        l_fu_1042_p3 = 32'd20;
    end else if (p_Result_313_fu_1032_p4[21] == 1'b1) begin
        l_fu_1042_p3 = 32'd21;
    end else if (p_Result_313_fu_1032_p4[22] == 1'b1) begin
        l_fu_1042_p3 = 32'd22;
    end else if (p_Result_313_fu_1032_p4[23] == 1'b1) begin
        l_fu_1042_p3 = 32'd23;
    end else if (p_Result_313_fu_1032_p4[24] == 1'b1) begin
        l_fu_1042_p3 = 32'd24;
    end else if (p_Result_313_fu_1032_p4[25] == 1'b1) begin
        l_fu_1042_p3 = 32'd25;
    end else if (p_Result_313_fu_1032_p4[26] == 1'b1) begin
        l_fu_1042_p3 = 32'd26;
    end else if (p_Result_313_fu_1032_p4[27] == 1'b1) begin
        l_fu_1042_p3 = 32'd27;
    end else if (p_Result_313_fu_1032_p4[28] == 1'b1) begin
        l_fu_1042_p3 = 32'd28;
    end else if (p_Result_313_fu_1032_p4[29] == 1'b1) begin
        l_fu_1042_p3 = 32'd29;
    end else if (p_Result_313_fu_1032_p4[30] == 1'b1) begin
        l_fu_1042_p3 = 32'd30;
    end else if (p_Result_313_fu_1032_p4[31] == 1'b1) begin
        l_fu_1042_p3 = 32'd31;
    end else begin
        l_fu_1042_p3 = 32'd32;
    end
end

assign lsb_index_fu_1060_p2 = ($signed(sub_ln947_fu_1054_p2) + $signed(32'd4294967243));

assign lshr_ln950_fu_1100_p2 = 32'd4294967295 >> zext_ln950_fu_1096_p1;

assign lshr_ln961_fu_1198_p2 = zext_ln960_fu_1082_p1 >> zext_ln961_fu_1194_p1;

assign m_53_fu_1224_p2 = (m_fu_1212_p3 + zext_ln964_fu_1220_p1);

assign m_56_fu_1230_p4 = {{m_53_fu_1224_p2[63:1]}};

assign m_fu_1212_p3 = ((icmp_ln961_fu_1152_p2[0:0] == 1'b1) ? lshr_ln961_fu_1198_p2 : shl_ln962_fu_1174_p2);

assign or_ln443_4_fu_1393_p2 = (and_ln443_reg_1622_pp0_iter9_reg | and_ln443_4_fu_1388_p2);

assign or_ln443_fu_1354_p2 = (icmp_ln443_fu_1342_p2 | icmp_ln443_4_fu_1348_p2);

assign or_ln952_10_fu_1112_p2 = (shl_ln952_fu_1106_p2 | lshr_ln950_fu_1100_p2);

assign p1_fu_1413_p3 = ((or_ln443_4_reg_1648_pp0_iter11_reg[0:0] == 1'b1) ? 64'd13798997430714945504 : 64'd13854155686354486565);

assign p2_fu_1429_p3 = ((or_ln443_4_reg_1648_pp0_iter12_reg[0:0] == 1'b1) ? 64'd13822851435045880248 : 64'd4641977866302784411);

assign p3_fu_1445_p3 = ((or_ln443_4_reg_1648_pp0_iter14_reg[0:0] == 1'b1) ? 64'd13835960482696009560 : 64'd13866933838737128345);

assign p4_fu_1461_p3 = ((or_ln443_4_reg_1648_pp0_iter16_reg[0:0] == 1'b1) ? 64'd13836295942911834650 : 64'd4639072047187312667);

assign p5_fu_1477_p3 = ((or_ln443_4_reg_1648_pp0_iter18_reg[0:0] == 1'b1) ? 64'd4616611452376731079 : 64'd13852696627858410445);

assign p6_fu_1492_p3 = ((or_ln443_4_reg_1648_pp0_iter20_reg[0:0] == 1'b1) ? 64'd4613798575908835234 : 64'd4612826843888178297);

assign p_Result_312_fu_740_p1 = p_Val2_172_fu_304[0:0];

integer ap_tvar_int_0;

always @ (pre_result_V_fu_1020_p2) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_313_fu_1032_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_313_fu_1032_p4[ap_tvar_int_0] = pre_result_V_fu_1020_p2[31 - ap_tvar_int_0];
        end
    end
end

assign p_Result_314_fu_1144_p3 = pre_result_V_fu_1020_p2[lsb_index_fu_1060_p2];

assign p_Result_315_fu_1280_p5 = {{tmp_fu_1272_p3}, {zext_ln965_fu_1240_p1[51:0]}};

assign p_Result_s_fu_1244_p3 = m_53_fu_1224_p2[32'd54];

assign p_cast13_fu_662_p1 = j_fu_300;

assign pre_result_V_51_fu_828_p2 = (zext_ln1691_fu_824_p1 ^ ret_42_fu_780_p2);

assign pre_result_V_52_fu_948_p2 = (ret_fu_908_p19 ^ pre_result_V_51_fu_828_p2);

assign pre_result_V_53_fu_1000_p2 = (ret_40_fu_984_p7 ^ pre_result_V_52_fu_948_p2);

assign pre_result_V_fu_1020_p2 = (zext_ln1691_11_fu_1016_p1 ^ pre_result_V_53_fu_1000_p2);

assign q1_fu_1421_p3 = ((or_ln443_4_reg_1648_pp0_iter11_reg[0:0] == 1'b1) ? 64'd4575625165243457492 : 64'd13856235683484533956);

assign q2_fu_1437_p3 = ((or_ln443_4_reg_1648_pp0_iter12_reg[0:0] == 1'b1) ? 64'd4599480671287182180 : 64'd4639889312772538999);

assign q3_fu_1453_p3 = ((or_ln443_4_reg_1648_pp0_iter14_reg[0:0] == 1'b1) ? 64'd4612688371394471446 : 64'd13863054224260258002);

assign q4_fu_1469_p3 = ((or_ln443_4_reg_1648_pp0_iter16_reg[0:0] == 1'b1) ? 64'd4615636595525398809 : 64'd4634401141363829182);

assign r_14_fu_1006_p4 = {{pre_result_V_53_fu_1000_p2[31:18]}};

assign r_21_fu_1405_p3 = ((or_ln443_4_reg_1648_pp0_iter11_reg[0:0] == 1'b1) ? z_10_reg_1673 : grp_fu_1141_p_dout0);

assign r_22_fu_797_p3 = {{7'd39}, {tmp_77_fu_788_p4}};

assign r_fu_814_p4 = {{ret_42_fu_780_p2[31:11]}};

assign r_s_fu_682_p4 = {{addr_head_p_3_V_fu_670_p2[3:1]}};

assign result_fu_1527_p3 = ((or_ln443_4_reg_1648_pp0_iter27_reg[0:0] == 1'b1) ? select_ln540_fu_1520_p3 : grp_fu_1081_p_dout0);

assign ret_40_fu_984_p7 = {{{{{{tmp_81_fu_954_p4}, {1'd0}}, {tmp_82_fu_964_p4}}, {3'd0}}, {tmp_83_fu_974_p4}}, {17'd0}};

assign ret_42_fu_780_p2 = (zext_ln1043_fu_762_p1 ^ xor_ln1544_fu_774_p2);

assign ret_fu_908_p19 = {{{{{{{{{{{{{{{{{{tmp_464_fu_834_p3}, {2'd0}}, {tmp_78_fu_842_p4}}, {1'd0}}, {tmp_465_fu_852_p3}}, {2'd0}}, {tmp_466_fu_860_p3}}, {1'd0}}, {tmp_79_fu_868_p4}}, {3'd0}}, {tmp_467_fu_878_p3}}, {1'd0}}, {tmp_468_fu_886_p3}}, {1'd0}}, {tmp_80_fu_894_p4}}, {1'd0}}, {trunc_ln1542_fu_904_p1}}, {7'd0}};

assign select_ln540_fu_1520_p3 = ((and_ln443_reg_1622_pp0_iter27_reg[0:0] == 1'b1) ? grp_fu_1081_p_dout0 : bitcast_ln541_4_fu_1516_p1);

assign select_ln722_fu_766_p3 = ((p_Result_312_fu_740_p1[0:0] == 1'b1) ? 32'd2567483615 : 32'd0);

assign select_ln949_fu_1180_p3 = ((icmp_ln949_fu_1076_p2[0:0] == 1'b1) ? icmp_ln952_fu_1124_p2 : p_Result_314_fu_1144_p3);

assign select_ln961_fu_1204_p3 = ((icmp_ln961_fu_1152_p2[0:0] == 1'b1) ? select_ln949_fu_1180_p3 : and_ln952_13_fu_1158_p2);

assign select_ln968_fu_1264_p3 = ((p_Result_s_fu_1244_p3[0:0] == 1'b1) ? add_ln968_fu_1258_p2 : sub_ln969_fu_1252_p2);

assign sext_ln587_fu_708_p1 = $signed(trunc_ln_fu_692_p4);

assign shl_ln952_fu_1106_p2 = 32'd1 << lsb_index_fu_1060_p2;

assign shl_ln962_fu_1174_p2 = zext_ln960_fu_1082_p1 << zext_ln962_fu_1170_p1;

assign sub_ln947_fu_1054_p2 = (32'd32 - l_fu_1042_p3);

assign sub_ln950_fu_1090_p2 = (6'd22 - trunc_ln950_fu_1086_p1);

assign sub_ln962_fu_1164_p2 = (32'd54 - sub_ln947_fu_1054_p2);

assign sub_ln969_fu_1252_p2 = (11'd1022 - trunc_ln946_fu_1050_p1);

assign t3_fu_1383_p1 = xor_ln456_fu_1377_p2;

assign tmp_22_fu_1328_p4 = {{bitcast_ln443_fu_1325_p1[62:52]}};

assign tmp_463_fu_732_p3 = p_Val2_s_fu_296[32'd31];

assign tmp_464_fu_834_p3 = pre_result_V_51_fu_828_p2[32'd24];

assign tmp_465_fu_852_p3 = pre_result_V_51_fu_828_p2[32'd17];

assign tmp_466_fu_860_p3 = pre_result_V_51_fu_828_p2[32'd14];

assign tmp_467_fu_878_p3 = pre_result_V_51_fu_828_p2[32'd7];

assign tmp_468_fu_886_p3 = pre_result_V_51_fu_828_p2[32'd5];

assign tmp_469_fu_1066_p4 = {{lsb_index_fu_1060_p2[31:1]}};

assign tmp_470_fu_1130_p3 = lsb_index_fu_1060_p2[32'd31];

assign tmp_472_fu_1366_p3 = ((and_ln443_fu_1360_p2[0:0] == 1'b1) ? tmp_uniform_reg_1607 : grp_fu_1089_p_dout0);

assign tmp_77_fu_788_p4 = {{j_6_reg_1573[3:1]}};

assign tmp_78_fu_842_p4 = {{pre_result_V_51_fu_828_p2[21:19]}};

assign tmp_79_fu_868_p4 = {{pre_result_V_51_fu_828_p2[12:11]}};

assign tmp_80_fu_894_p4 = {{pre_result_V_51_fu_828_p2[3:2]}};

assign tmp_81_fu_954_p4 = {{pre_result_V_52_fu_948_p2[16:14]}};

assign tmp_82_fu_964_p4 = {{pre_result_V_52_fu_948_p2[12:7]}};

assign tmp_83_fu_974_p4 = {{pre_result_V_52_fu_948_p2[3:2]}};

assign tmp_V_fu_754_p3 = {{tmp_463_fu_732_p3}, {tmp_s_fu_744_p4}};

assign tmp_fu_1272_p3 = {{1'd0}, {select_ln968_fu_1264_p3}};

assign tmp_s_fu_744_p4 = {{p_Val2_172_fu_304[30:1]}};

assign tmp_uniform_fu_1296_p3 = ((icmp_ln938_fu_1026_p2[0:0] == 1'b1) ? 64'd0 : bitcast_ln746_fu_1292_p1);

assign trunc_ln1542_fu_904_p1 = pre_result_V_51_fu_828_p2[0:0];

assign trunc_ln229_fu_666_p1 = j_fu_300[0:0];

assign trunc_ln443_fu_1338_p1 = bitcast_ln443_fu_1325_p1[51:0];

assign trunc_ln946_fu_1050_p1 = l_fu_1042_p3[10:0];

assign trunc_ln950_fu_1086_p1 = sub_ln947_fu_1054_p2[5:0];

assign trunc_ln_fu_692_p4 = {{addr_head_p_m_p_1_V_fu_676_p2[7:1]}};

assign xor_ln1544_fu_774_p2 = (select_ln722_fu_766_p3 ^ lhs_V_fu_292);

assign xor_ln456_fu_1377_p2 = (bitcast_ln456_fu_1374_p1 ^ 64'd9223372036854775808);

assign xor_ln541_fu_1510_p2 = (bitcast_ln541_fu_1506_p1 ^ 64'd9223372036854775808);

assign xor_ln952_fu_1138_p2 = (tmp_470_fu_1130_p3 ^ 1'd1);

assign z_9_fu_1398_p3 = ((or_ln443_4_reg_1648[0:0] == 1'b1) ? grp_fu_1189_p_dout0 : grp_fu_1093_p_dout0);

assign zext_ln1043_fu_762_p1 = tmp_V_fu_754_p3;

assign zext_ln1691_11_fu_1016_p1 = r_14_fu_1006_p4;

assign zext_ln1691_fu_824_p1 = r_fu_814_p4;

assign zext_ln587_8_fu_712_p1 = $unsigned(sext_ln587_fu_708_p1);

assign zext_ln587_9_fu_805_p1 = r_22_fu_797_p3;

assign zext_ln587_fu_702_p1 = r_s_fu_682_p4;

assign zext_ln950_fu_1096_p1 = sub_ln950_fu_1090_p2;

assign zext_ln960_fu_1082_p1 = pre_result_V_fu_1020_p2;

assign zext_ln961_fu_1194_p1 = add_ln961_fu_1188_p2;

assign zext_ln962_fu_1170_p1 = sub_ln962_fu_1164_p2;

assign zext_ln964_fu_1220_p1 = select_ln961_fu_1204_p3;

assign zext_ln965_fu_1240_p1 = m_56_fu_1230_p4;

always @ (posedge ap_clk) begin
    j_cast_reg_1859[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_cast_reg_1859_pp0_iter34_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //TOP_AWGN
